### ISSUE TITLE
Edit cake

### ISSUE THREAD

**Issue by aberracja** [GirlsCodersWarsaw/CakeMaster_Ania#5]
_As a User I want to edit cake attributes_

*Acceptance Criteria*
* [x] on homepage when I click on name of the cake I want to be redirected to edit page for cakes
* [x] on edit page I want to be able to edit name, type and description of a cake

**Comment by Czarrrna** [comment]
Done.
https://github.com/GirlsCodersWarsaw/CakeMaster_Ania/commit/c300f21979183603948ad545b601cb0088045555

**Comment by pjar** [comment]
@Czarrrna additionally - please extract collection partial from index template

**Comment by Czarrrna** [comment]
https://github.com/GirlsCodersWarsaw/CakeMaster_Ania/commit/cb88cd9980ed3289a620a5b1fa83ac4c067a9b2b
https://github.com/GirlsCodersWarsaw/CakeMaster_Ania/commit/a80440bc1be08b5a810edf7f18b6d68c77b7d0f7

**Comment by Czarrrna** [comment]
Should I open a pull request for this?

**Comment by pjar** [comment]
It's already open ;)
