### ISSUE TITLE
Delete cake

### ISSUE THREAD

**Issue by aberracja** [GirlsCodersWarsaw/CakeMaster_Ania#6]
_As a User I want to be able to delete cake_

*Acceptance Criteria*
* [x] next to name of a cake I want to have a button to delete cake
* [x] when I click on button I want cake to be deleted

**Comment by Czarrrna** [comment]
Done. https://github.com/GirlsCodersWarsaw/CakeMaster_Ania/commit/a8bb0a703c424566be0054822e753b448512f35d

**Comment by Czarrrna** [comment]
Need new issues for cake_master! 
cc/ @aberracja

**Comment by Czarrrna** [comment]
* [ ] add helper for errors
